export const types = {
  SET_FLIGHT: "SET_FLIGHT",
  SET_FLIGHTS: "SET_FLIGHTS",
  SET_REGISTRATION: "SET_REGISTRATION",
  SET_TYPE: "SET_TYPE",
  SET_DATE_ARRIVAL: "SET_DATE_ARRIVAL",
  SET_DATE_DEPARTURE: "SET_DATE_DEPARTURE",
  SET_FLIGHT_NUMBER: "SET_FLIGHT_NUMBER",
  SET_DELETE: "SET_DELETE",
};
