version: '3.8'

services:
  db:
    image: mysql
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
#    expose:
#      - "3306"
volumes:
  mysqldb: